pipeline:

steps:

- name: build
  image: node:latest
  commands:
    - "npm install"

- name: publish  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: kharloss/repo
    auto_tag: true
    auto_tag_suffix: drone-build